### ISSUE TITLE
关于Author.activity的url需求

### ISSUE THREAD

**Issue by SimplyY** [7sDream/zhihu-py3#11]
![image](https://cloud.githubusercontent.com/assets/8455579/8852588/ae80d000-3188-11e5-93fe-571cc76bc670.png)

如图其实每一个activity都是有url的，之前我说的新需求：*回答的url*。其实这个需求没有思考清楚。

我想要的是这种无区别的url，在每一个activity里的，作为我加载单个feed的webview的参数。

**Comment by 7sDream** [comment]
dev分支下，已将所有类的url属性重构为public

可用以下代码获取到每个act的url

```python
attrs = ['question', 'answer', 'column', 'post', 'topic']
for act in author.activities:
    for attr in attrs:
        if getattr(act, attr) is not None:
            print(getattr(act, attr).url)
```
