### ISSUE TITLE
setuptools 打包

### ISSUE THREAD

**Issue by xen0n** [7sDream/zhihu-py3#13]
准备写打包 patch (方便用 pip 管理), 需要这些信息:

* 版本号
* 许可证

在这回复就行了, 我在自己的 branch 已经调整了项目结构, 到时候自己写进去就行, 这样就省得 merge 蛋疼了

**Comment by 7sDream** [comment]
我回来了……开始去看电影了……

你这边先pr的话我dev分支还得rebase下，也一样……恩，反正都要解决冲突，随意啦，你先patch吧

---

版本号就从 0.1 开始

对于许可证方面因为不是单纯搞开源，所以不是很清楚，我参考的是这张图

![开源许可证选择](http://image.beekka.com/blog/201105/bg2011050101.png)

那我就选MIT好了～
