### ISSUE TITLE
建议增加获取最近动态和关注者的功能

### ISSUE THREAD

**Issue by SimplyY** [7sDream/zhihu-py3#2]
##  你的TODO:

![image](https://cloud.githubusercontent.com/assets/8455579/8498960/ca6d48c6-21bf-11e5-9b07-5b360839482c.png)

## help

我需要一个新的功能——某个用户的最新动态，，求开发。列列我的设想，以后应该还有合作。

ps：你的库好用啊，而且用pydoc看到的文档，写的真不错，点个赞

**Comment by 7sDream** [comment]
嗯嗯 代码能帮上你忙我也很开心哒，需求我尽量完成。

> 我需要一个新的功能——某个用户的最新动态

意思我懂，细节再解释一下吧，最好给一个需要的接口定义吧。

大概意思就是要在`Author`类中增加几个功能是吧，获取最近的回答？如果没记错的话是有这个功能的呀，使用`author.answer`返回的生成器就行了，想获取几个就用几次`next()`呗。如果不是这个需求的话，给出需要的函数的功能吧。

最近的文章这个可能有点难，因为知乎用户的文章是分专栏的，并不能简单的知道这几个专栏作者最后发到了哪个，不过专栏这部分知乎有API，我暑假去尽量看看吧。

然而需要的关注提醒，发notification这个就是你的代码里需要做的事情啦，比如隔时轮询嘛，然后和上一次取到的资料对比，如果发现有更新就提示，这个得你自己来咯。

有什么不清楚的请随意提啦，这个模块好像停久没更新了，正好完善下。

**Comment by SimplyY** [comment]
之前以为你知道，我说的最新动态是这个：

![image](https://cloud.githubusercontent.com/assets/8455579/8507461/c4ce95fc-2276-11e5-9d9f-62cada52540c.png)



不知道好不好做。

然后接口上需要一个新类感觉，名字可以和github类似用`feed`。

实现大概是这样：
1. 从`Author`类中的方法返回`feed`生成器。
2. `feed`中有两个属性：`action`（类型可以是枚举，点赞or关注or发表）、`content`（类型是`Question`or`Answer`or`Article`）

其实我python很渣的...感觉我可能说错了很多。。。。
我的调用示例：

```python
feeds = zhihu.Author(url).feeds

for feed in feeds:
	print(feed.action)
	content = feed.content
	if 	type(content) == Question:
		....
	elif type(content) == Answer:
		....
	elif type(content) == Article:
		....
```
大概这样.

求指点。

**Comment by 7sDream** [comment]
懂了

等我暑假吧，现在学校有个Android项目要写，估计只有回家才能继续维护这个项目啦~

实现起来应该不难，嗯嗯。

我去加TODO。

**Comment by SimplyY** [comment]
学了好几天pyqt，大概把流程和要用的东西弄清了。
不过突然发现需要**用户关注者**，作为添加额外关注的借口，暑假请优先开发这个~

我那个项目大概设想在这里，求意见~
https://github.com/SimplyY/zhihu_pyqt
https://github.com/SimplyY/zhihu_pyqt/issues/1

**Comment by 7sDream** [comment]
是**关注了哪些人**还是**被哪些人关注了**呢？

**Comment by buzouxun** [comment]
关于“最新动态”这个feature，已发pull request。但我没有做 feed ，没创建feed的类。zhihu_pyqt 听起来不错，加油哈！

**Comment by SimplyY** [comment]
@buzouxun 话说这个功能是你在写了么，我zhihu_pyqt写了将近一半了，，
求feed类的action、time、content属性。

**Comment by buzouxun** [comment]
@SimplyY  我懂你的意思，我现在不在写。我没有写的原因是，有至少两种不同的 code implementation 来实现这个功能，我不是很清楚到底怎么搞比较好。
@7sDream ，如果 7sDream 最近放假回国了，那就让他来决定怎么 implement 和 code 。如果 7sDream 没有时间，我们可以在这里讨论一下，然后我可以code 写。
SimplyY,  先看 7sDream 的回复吧

**Comment by SimplyY** [comment]
哦哦，这样啊。

他竟然出国了！去哪了，这么6

**Comment by buzouxun** [comment]
@SimplyY  我猜的哈~

**Comment by 7sDream** [comment]
然而并没有Q^Q

刚回家忙着探亲戚去了 爷爷奶奶外公外婆啥的 今晚应该回家 有时间来讨论一下。

咱还是弄个即时交流的方式吧 比较好集中讨论问题。

觉得弄讨论组、QQ群还是IRC呢？

中午还得去姑姑家吃饭ヽ(≧Д≦)ノ……待我下午回去详谈T^T

**Comment by SimplyY** [comment]
qq吧，，irc我今天刚卸掉。。主要是别人聊英文我都看不懂，今天一看几个月没用就卸掉了。。。。

**Comment by 7sDream** [comment]
行，email我你的QQ吧 我晚上回家弄个讨论组。

@buzuoxun 来讨论的话也Email我你的QQ哈

估计7点到家。唉咻😞

**Comment by 7sDream** [comment]
终于写完获取关注者了，可以关Issue了~
