### ISSUE TITLE
为啥我测试下载所有答案时图片链接错误？

### ISSUE THREAD

**Issue by wplct** [7sDream/zhihu-py3#24]
<img src="//pic2.zhimg.com/15cf95daf77b49fc6b2ad363942a05a9_r.jpg"/>

**Comment by wplct** [comment]
<img src="//pic2.zhimg.com/15cf95daf77b49fc6b2ad363942a05a9_r.jpg"/>

**Comment by 7sDream** [comment]
知乎前端改了，下一个版本会修复。
