### ISSUE TITLE
client.photo_url中的获取关注人的头像链接错误.

### ISSUE THREAD

**Issue by ilumer** [7sDream/zhihu-py3#26]
我根据vczh的那个测试下来发生错误error
     No connection adapters were found for 
    'http:https://xxxxxxxx  知乎的链接方式改了吧

**Comment by 7sDream** [comment]
应该是又改了。等下次更新来修复吧。

然而恰巧我电脑又坏了，估计没什么时间改。Q^Q 急着用的话可以先把 `common.py` 这个文件里的 `PROTOCOL` 改成空字符串试试吧⊙ω⊙。

**Comment by ilumer** [comment]
不影响使用，只是新手想问一下这些API怎么分析出来的啊，如果自己分析一个需要哪些技能点啊

**Comment by 7sDream** [comment]
是指类似 `/node/ProfileFolloweesListV2`  这样的东西和所需参数么？需要的技能点也没啥。http 基础知识（GET POST 啥的），URL 字符编码，JSON 格式，然后加上一个有 network 功能的浏览器（ff,chrome,ie现在都有）就行了。
