### ISSUE TITLE
是否考虑添加采集评论的功能？

### ISSUE THREAD

**Issue by laike9m** [7sDream/zhihu-py3#29]
现在 Answer 类是不包含评论的，有增加的打算么？

**Comment by 7sDream** [comment]
看情况

这个学期的课程非常多而且重 最近不是很有时间写代码 PR都没时间去看 估计得等周末

如果我闲下来了 基本上有需求的话我就会去写

另外 有能力的话 欢迎PR

**Comment by laike9m** [comment]
最近急着用，我看看能不能加吧。有没有什么规范或者 test case 怎么写之类的文档？

**Comment by 7sDream** [comment]
代码尽量 PEP8 吧 其他的规范倒是少（因为数据是从网上获取而且经常变 所以 unitest 的写法还在讨论 参见另一个issue）

你可以先fork着自己加功能 不着急PR

**Comment by 7sDream** [comment]
已实现简易的评论采集功能～
