### ISSUE TITLE
登录方法失效

### ISSUE THREAD

**Issue by kehao95** [7sDream/zhihu-py3#3]
验证码部分好像已经失效了
具体到```login(email,password,captcha)```
<Response [405]>
可能需要考虑改进登录方法

**Comment by 7sDream** [comment]
知乎的登录好像最近加了个可以用手机登录的方式，所以尝试登录的网址从
http://www.zhihu.com/login
变成了：
http://www.zhihu.com/login/email
和
http://www.zhihu.com/login/phone_num

马上我去改一下，发个hotfix.

**Comment by 7sDream** [comment]
已发hotfix，关闭issue，有新Bug请另开Issue。
