### ISSUE TITLE
答案状态是不友善内容时出错

### ISSUE THREAD

**Issue by littlezz** [7sDream/zhihu-py3#38]
在Answer类中，不友善时content为空， `answer_content_process`里面的`clone_bs4_elem`函数在输入为`None`时出错。

**Comment by littlezz** [comment]
还有不能公开讨论的之类的答案也会。。。总之被河蟹了的都会， 在content方法里面判断一下

**Comment by 7sDream** [comment]
收到了，下个版本一起改，thx 反馈。
（周五统一修bug TAT 上课太忙）

**Comment by 7sDream** [comment]
可PR的话也非常欢迎。（另外readme最后那个群也欢迎加入）

**Comment by littlezz** [comment]
血崩， 没有记下不友善内容答案的url， 现在找一个不友善的答案好难  


![image](https://cloud.githubusercontent.com/assets/7009837/11316395/775acc68-9040-11e5-8149-bd078fd43781.png)

**Comment by 7sDream** [comment]
已merge，应该是修复了吧……
暂时关闭issue。
