### ISSUE TITLE
分离`_make_soup`的网络请求和处理， 提供`from_html`方法

### ISSUE THREAD

**Issue by littlezz** [7sDream/zhihu-py3#43]
其他地方有待分离
我的想法是所有的类都继承一个BaseZhihu，  里面增加from_html

**Comment by littlezz** [comment]
分离的最主要的目的是为了让类可以用于解析html， http请求的部分通过其他的方法来操控。 目前的http的请求无法控制， 限制比较大。

然后还有一个就是希望`class_common_init`中总是允许None通过检查，  如果只是用于解析html的话， url传入None应该是合法的。

**Comment by 7sDream** [comment]
PR收到～～

然而～一律PR到 dev 分支呀～～

**Comment by kehao95** [comment]
网络请求分离以后有没有可能支持异步请求处理的分支？
现在的网络请求都是阻塞的，添加异步以后可以大大加快速度。
在另一个项目做过类似的实验[python异步-实战](http://kehao.me/2015/python%E5%BC%82%E6%AD%A5-%E5%AE%9E%E6%88%98-2/ )

当然也有一定风险：
包装成协程的话用法就有点扭曲了。
速度过快的话更容易触发反爬虫机制。

所以可能的选择是将其另外作为一个特色的分支。

**Comment by 7sDream** [comment]
@kehao95 这个改的话基本上整个都要改～～等稳定了可以考虑OvO

**Comment by littlezz** [comment]
```python
# ... code
data = await r.text()
answer = zhihu.Answer.from_html(data)

#...code 
```

把网络请求得到的数据传入`from_html`, 可以得到相应的实例， 然后正常的操作就好了。

**Comment by littlezz** [comment]
我加了一段文档来说明， 目前看来使用起来还是有点麻烦的  

#51

**Comment by 7sDream** [comment]
@littlezz 好样的！

**Comment by laike9m** [comment]
@kehao95 感觉可以作为一个 option 提供
