### ISSUE TITLE
文档类的文件为何都是 rst 格式？

### ISSUE THREAD

**Issue by NearTan** [7sDream/zhihu-py3#52]
个人认为 markdown 在 GitHub 上能有更好的渲染，比如 rst 的 check box 就不能渲染出来
使用 rst 是不是作者个人喜好？

**Comment by 7sDream** [comment]
答：不是。其实一开始都是 md 的一方面是因为 pypi 的介绍要求用 rst 格式

**Comment by 7sDream** [comment]
唔，突然觉得可以写的时候 markdown，release 的时候在 setup.py 里用 pandoc 转成 rst 就好嘛……我真是傻 - -
