### ISSUE TITLE
class 继承 object

### ISSUE THREAD

**Issue by flyer103** [7sDream/zhihu-py3#61]
建议所有的 class 都继承 object，不要用老式的 class 定义方法：[Python class inherits object](http://stackoverflow.com/questions/4015417/python-class-inherits-object)

**Comment by 7sDream** [comment]
![image](https://cloud.githubusercontent.com/assets/7822577/12016928/a5d81ba0-ad8b-11e5-8c0f-d8f4d82faaa0.png)

如果没有需要继承的类的情况下，我们都是用的木有括号的写法，所以其实也是新式滴~~

**Comment by flyer103** [comment]
嗯，显式声明？:D

**Comment by 7sDream** [comment]
嗯，确实这样比较规范，会注意的~~

（下次commit和 #60 一起改~

**Comment by flyer103** [comment]
👍
