### ISSUE TITLE
beautifulsoup 换为 lxml

### ISSUE THREAD

**Issue by flyer103** [7sDream/zhihu-py3#62]
[Parsing HTML in python - lxml or BeautifulSoup? Which of these is better for what kinds of purposes?](http://stackoverflow.com/questions/1922032/parsing-html-in-python-lxml-or-beautifulsoup-which-of-these-is-better-for-wha)

**Comment by 7sDream** [comment]
lxml在windows下安装有点麻烦~~bs内部也是用的lxml，所以暂时不考虑替换~

**Comment by flyer103** [comment]
嗯，lxml 安装确实有些麻烦，可以考虑使用 docker 封装为一个 image，尽量减少环境依赖的问题。
