### ISSUE TITLE
觉得专栏叫 Column 比较恰当吧

### ISSUE THREAD

**Issue by buzouxun** [7sDream/zhihu-py3#7]
Book 感觉就是书而已，而已说不定知乎出书了，还有的写

"any one of two or more sections of print that appear next to each other on a page and are separated by a blank space or a line" from http://www.merriam-webster.com/dictionary/column 

不过也不是什么大问题就是了，随作者吧

**Comment by 7sDream** [comment]
确实，知乎的API里也用的Column，文章是用的Post……我也在考虑要不要改一下

要不目前暂时用Alias？

Column = Book
Post = Article

这样？

欢迎讨论…………

反正现在这Modole也没很多人用……也不需要太多向前兼容？（吧？）

大家讨论下吧。

**Comment by 7sDream** [comment]
已改。
