### ISSUE TITLE
现在知乎登陆不需要验证码了

### ISSUE THREAD

**Issue by lyyyuna** [7sDream/zhihu-py3#74]
实测只用 email 和 password 也能登陆。
1. email, password, _xsrf 登陆之后
2. GET /
3. set-cookies 会返回一个新 _xsrf,

**Comment by 7sDream** [comment]
因为要保证可用性，所以只要有会出验证码的情况，验证码逻辑还是实现一下比较好。

请在不常用地区，或者进行多次使用错误密码登录的测试吧。

如果还是不要验证码，请再次在这里回复~谢谢~

然而还在上课，如果有时间的情况下，也许会更新下代码自动判断需不需要验证码……Thx 反馈，会加入 To do list 的。

**Comment by lyyyuna** [comment]
不同地域的测试有限，希望之后有人看到能多测试。
在每次清 cookies，多次登陆的情况下仍是该 html。
========================
另，在手机号登陆的情况下，虽然 j['r'] == 1，但其实也是登陆成功的。

**Comment by 7sDream** [comment]
新版本默认登录不用验证码辣~当然有参数可以控制是否要输入验证码~
