### ISSUE TITLE
请问手机号登录的地址是什么啊？

### ISSUE THREAD

**Issue by litterzhang** [7sDream/zhihu-py3#76]
使用手机号登录，会返回 r=1

**Comment by 7sDream** [comment]
好象是把email改成phone什么的 我不是很记得了……你可以F12看看

**Comment by zhangwei19940824** [comment]
是把email改成phone_num，知乎登录好像确实不要验证码

**Comment by 7sDream** [comment]
@zhangwei19940824 

好的~我发布新版本的时候去掉验证码~Thanks~
