### ISSUE TITLE
使用Topic类下的children方法无法获得全部子话题

### ISSUE THREAD

**Issue by tzhao0311** [7sDream/zhihu-py3#77]
你好！Topic类的children方法无法获得某话题下的全部子话题，因为许多话题的子话题很多，当前页面显示不完，所以需要点击“加载更多”才能显示更多的子话题。而目前的children方法只能获得某话题页面中初始显示的那些话题。例如：「形而上」话题有44个子话题，而通过children方法只能获得其中的10个子话题。
![image](https://cloud.githubusercontent.com/assets/15905709/14156281/e6a9bd72-f6c5-11e5-9c46-5f233359a65f.png)

**Comment by 7sDream** [comment]
原来如此，晚上修复，感谢提出！

**Comment by 7sDream** [comment]
等一下，我去看了下代码，应该是可以获取到全部的，加载更多的逻辑我也实现了的。应该是你没有在代码里登录的原因，如果没有登录的话就无法获取到全部。

以下是截图，能获取到全部：
![Topic get children](http://ww1.sinaimg.cn/large/88e401f0jw1f2g21o9ussj211x0kc0xv.jpg)

**Comment by tzhao0311** [comment]
额，确实是，现在可以了，打扰LZ了，不好意思啊。
