### ISSUE TITLE
爬取某一问题的所有答案时，答案现实不全！

### ISSUE THREAD

**Issue by huluobotouer** [7sDream/zhihu-py3#78]
例如我在爬取[这个问题(https://www.zhihu.com/question/19969760)](https://www.zhihu.com/question/19969760)的所有答案时，原本有39个答案，但是只能爬取20个。而当我在这个问题的网页地址之后加入 `?sort=created` 使其变成`https://www.zhihu.com/question/19969760?sort=created`，再进行爬取时就能爬取所有的39个答案。

ps，我是初学者，就是个渣渣，如果不对，就忽视吧

**Comment by laike9m** [comment]
显然是因为知乎加入分页之后导致原始的接口没法返回所有问题了。你先用 sort 吧，那个处理了答案分页。

**Comment by 7sDream** [comment]
喵，待我晚上去写一哈……

**Comment by 7sDream** [comment]
唔……我今天好困，于是我决定明天再写 =，=

**Comment by 7sDream** [comment]
写完了，更新到 0.3.17 试试吧……

如果没问题记得关 Issue……
