### ISSUE TITLE
Topic类下questions生成器的疑问

### ISSUE THREAD

**Issue by Link-KS** [7sDream/zhihu-py3#82]
你好！谢谢你写的程序。我是个初学者，觉得受益匪浅，但现在对Topic类下的questions生成器有点疑问。不知道为什么用topic.questions.__next__()或者next(topic.questions) 出来的全部是同一个问题，而for question in topic.questions就不会这样。请问这是为什么呢？
另外，今天我试着爬了200多个之后就出现了错误，打开浏览器发现要求输入验证码了。这种反爬虫的机制除了暂停程序之外应该怎么对付呀？

p.s. 希望zhihu-oauth那边能够对topic类加入questions生成器 >_<

**Comment by wplct** [comment]
该项目因为作者心累已经停止支持，请右转https://github.com/7sDream/zhihu-oauth
作者的另一个项目

**Comment by 7sDream** [comment]
@Link-KS 

你应该这样：

```python
question = topic.questions
next(question)
next(question)
# ...
```

你每次都用 topic.questions 那就每次都生成的初始的那个问题了。

然后知乎爬虫限制我也没办法呀，知乎是慢慢的开始注意这方面了。

然后因为 zhihu-oauth 用的是手机 APP 的接口，我暂时没有发现手机上怎么看话题下的所有问题，所以也没办法加入questions生成器。现在只能暂时先用着 unanswered_questions 吧。

http://zhihu-oauth.readthedocs.io/zh_CN/latest/for-user/zhcls/topic.html#zhihu_oauth.zhcls.topic.Topic.unanswered_questions

**Comment by Link-KS** [comment]
谢谢~！
